
definitions:
  steps:

    - step: &build
        image: node:18-alpine
        name: 'Build'
        caches:
          - node
        script:

          - echo "Building the application"
          - npm install

          - export DEPLOYMENT_DIR=./out
          - export NEXT_PUBLIC_LOGIN_URL=%%NEXT_PUBLIC_LOGIN_URL%%
          - export NEXT_PUBLIC_REGISTER_URL=%%NEXT_PUBLIC_REGISTER_URL%%
          - npm run build

          - |
            cat <<EOF > ${DEPLOYMENT_DIR}/version.html
            <!DOCTYPE html>
            <html>
            <head>
                <title>Version Information</title>
            </head>
            <body>
                <h1>Version Information</h1>
                <p>Commit Number: $BITBUCKET_COMMIT</p>
                <p>Branch Name: $BITBUCKET_BRANCH</p>
            </body>
            </html>
            EOF

          - ls -la ./

        artifacts:
          - .next
          - .next./**
          - out
          - out/**

    - step: &deploy-staging
        image: amazon/aws-cli:2.15.13 
        name: 'Deployment to Staging'
        deployment: development
        script:
          - echo "Deploying to ${AWS_BUCKET_NAME}"
          - export DEPLOYMENT_DIR=./out
          - ls -la 

          - |
            function replace() {
              placeholder=$1
              replacement=$2
              find ${DEPLOYMENT_DIR} -type f | xargs sed -i "s|%%${placeholder}%%|${replacement}|g"
            }
            replace NEXT_PUBLIC_LOGIN_URL "https://app.tbe.io/auth/login"
            replace NEXT_PUBLIC_REGISTER_URL "https://app.myblockchainid.io/auth/register"

          - aws s3 sync ${DEPLOYMENT_DIR} s3://${AWS_BUCKET_NAME} --delete --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --acl public-read


pipelines:

  default:    
    - step: *build 

  branches:
    dev:
      - step: *build 
      - step: *deploy-staging 
