import "@/Assets/css/index.css";
import type { Metadata } from "next";

// Components
import NavBar from "@/Components/Advanced/NavBar/NavBar";
import Footer from "@/Components/Advanced/Footer/Footer";
import GoTop from "@/Components/Advanced/GoTop/GoTop";
import CookieManager from "@/Components/Advanced/CookieManager/CookieManager";
import Script from "next/script";

// Data
import config from "@/data/config";

export const metadata: Metadata = {
  title: {
    template: `${config.WEBSITE_NAME} | %s`,
    default: `${config.WEBSITE_NAME}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-MD6WNEGVCB"
        ></Script>
        <Script id="head-ga">
          {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'G-MD6WNEGVCB');
            
           `}
        </Script>
      </head>
      <body>
        <NavBar />
        {children}
        <CookieManager />
        <GoTop />
        <Footer />
      </body>
    </html>
  );
}
